#ifndef UIVIEWCONTROLLER_GLOBAL_H
#define UIVIEWCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef UIVIEWCONTROLLER_LIB
# define UIVIEWCONTROLLER_EXPORT Q_DECL_EXPORT
#else
# define UIVIEWCONTROLLER_EXPORT Q_DECL_IMPORT
#endif

#endif // UIVIEWCONTROLLER_GLOBAL_H
