#ifndef IMAGEPROCESSING_GLOBAL_H
#define IMAGEPROCESSING_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef IMAGEPROCESSING_LIB
# define IMAGEPROCESSING_EXPORT Q_DECL_EXPORT
#else
# define IMAGEPROCESSING_EXPORT Q_DECL_IMPORT
#endif

#endif // IMAGEPROCESSING_GLOBAL_H
