#ifndef UIFRAME_GLOBAL_H
#define UIFRAME_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef UIFRAME_LIB
# define UIFRAME_EXPORT Q_DECL_EXPORT
#else
# define UIFRAME_EXPORT Q_DECL_IMPORT
#endif

#define MENUBAR_SIZE_MINIMIZE		0
#define MENUBAR_SIZE_TOP			90
#define MENUBAR_SIZE_LEFT			120
#define MENUBAR_SIZE_SEG			182
#define MENUBAR_SIZE_MIN			19

#define MENUBAR_SEG_LAYOUT_FULL		380
#define MENUBAR_SEG_LAYOUT_HALF		200

#define GENERALMENU_SIZE_HEIGHT				250
#define GENERALMENU_FLOATING_SIZE_HIEGHT	350

#endif // UIFRAME_GLOBAL_H
