#ifndef UICOMPONENT_GLOBAL_H
#define UICOMPONENT_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef UICOMPONENT_LIB
# define UICOMPONENT_EXPORT Q_DECL_EXPORT
#else
# define UICOMPONENT_EXPORT Q_DECL_IMPORT
#endif

#endif // UICOMPONENT_GLOBAL_H
